### ISSUE TITLE
Crash with cells with too much text - unknown limit...?

### ISSUE THREAD

**Issue by Fabiombolo** [ttsukagoshi/sheetsL#75]
Got an error when there is too much text to translate in one cell, but limit is unknown to the user

**Comment by ttsukagoshi** [comment]
@Fabiombolo Thanks for the heads-up, that would be a great idea💡 I'll work on it.

This limitation comes from the Google Apps Script's 2KB cap on the URL length in `UrlFetchApp.fetch`, in this case calling the DeepL API.
