### ISSUE TITLE
Error after first installation

### ISSUE THREAD

**Issue by Fabiombolo** [ttsukagoshi/sheetsL#76]
I had an already opened existing google sheet. I installed the app, set the api key, then I tried to set the language but got an error. Closed Chrome, restarted te same google sheet and then it was possible to set the language.

**Comment by ttsukagoshi** [comment]
Thank you for your input! I'll look into this, but this could be some internal issue in the Google Workspace itself...

**Comment by ttsukagoshi** [comment]
@Fabiombolo This is probably an issue where the add-on cannot correctly read its user property values in a Google Sheets file that was already open at the time of installation; in this case, the value saved in the user property is [the user's DeepL API authentication key](https://www.scriptable-assets.page/add-ons/sheetsl/#2-set-your-deepl-api-authentication-key).

I could not, however, verify the exact cause, nor could I work around this platform-level issue, so I've left a note for first-time users to reload the spreadsheet that you were already working on at the time of add-on's installation: https://www.scriptable-assets.page/add-ons/sheetsl/#3-set-your-target-language

Thank you again for your feedback!
